version: '3'

services:
  keycloak:
    image: jboss/keycloak:12.0.4
    container_name: keycloak
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
